/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BunkSetup { 'bunkName' : string, 'location' : string }
export interface CreditSettlement {
  'id' : bigint,
  'date' : string,
  'amountSettled' : number,
}
export interface DaySales {
  'id' : bigint,
  'pump1_n2_open' : number,
  'pump2_n1_close' : number,
  'dieselPrice' : number,
  'pump2_n2_close' : number,
  'pump2_n3_open' : number,
  'date' : string,
  'pump1_n1_close' : number,
  'testPetrol' : number,
  'pump2_n3_close' : number,
  'pump1_n3_open' : number,
  'pump2_n1_open' : number,
  'pump1_n2_close' : number,
  'pump2_n4_close' : number,
  'pump1_n1_open' : number,
  'creditGiven' : number,
  'pump2_n4_open' : number,
  'pump1_n3_close' : number,
  'pump1_n4_close' : number,
  'testDiesel' : number,
  'pump1_n4_open' : number,
  'pump2_n2_open' : number,
  'petrolPrice' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCreditSettlement' : ActorMethod<[string, number], undefined>,
  'addDaySales' : ActorMethod<
    [
      string,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteDaySalesByDate' : ActorMethod<[string], undefined>,
  'getAllDaySales' : ActorMethod<[], Array<DaySales>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCreditSettlements' : ActorMethod<
    [string, string],
    Array<CreditSettlement>
  >,
  'getDaySalesByDate' : ActorMethod<[string], [] | [DaySales]>,
  'getSetup' : ActorMethod<[], [] | [BunkSetup]>,
  'getTotalOutstandingCredit' : ActorMethod<[], number>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveSetup' : ActorMethod<[string, string], undefined>,
  'updateDaySales' : ActorMethod<
    [
      bigint,
      string,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
      number,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];