/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DaySales = IDL.Record({
  'id' : IDL.Nat,
  'pump1_n2_open' : IDL.Float64,
  'pump2_n1_close' : IDL.Float64,
  'dieselPrice' : IDL.Float64,
  'pump2_n2_close' : IDL.Float64,
  'pump2_n3_open' : IDL.Float64,
  'date' : IDL.Text,
  'pump1_n1_close' : IDL.Float64,
  'testPetrol' : IDL.Float64,
  'pump2_n3_close' : IDL.Float64,
  'pump1_n3_open' : IDL.Float64,
  'pump2_n1_open' : IDL.Float64,
  'pump1_n2_close' : IDL.Float64,
  'pump2_n4_close' : IDL.Float64,
  'pump1_n1_open' : IDL.Float64,
  'creditGiven' : IDL.Float64,
  'pump2_n4_open' : IDL.Float64,
  'pump1_n3_close' : IDL.Float64,
  'pump1_n4_close' : IDL.Float64,
  'testDiesel' : IDL.Float64,
  'pump1_n4_open' : IDL.Float64,
  'pump2_n2_open' : IDL.Float64,
  'petrolPrice' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CreditSettlement = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'amountSettled' : IDL.Float64,
});
export const BunkSetup = IDL.Record({
  'bunkName' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCreditSettlement' : IDL.Func([IDL.Text, IDL.Float64], [], []),
  'addDaySales' : IDL.Func(
      [
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteDaySalesByDate' : IDL.Func([IDL.Text], [], []),
  'getAllDaySales' : IDL.Func([], [IDL.Vec(DaySales)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCreditSettlements' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(CreditSettlement)],
      ['query'],
    ),
  'getDaySalesByDate' : IDL.Func([IDL.Text], [IDL.Opt(DaySales)], ['query']),
  'getSetup' : IDL.Func([], [IDL.Opt(BunkSetup)], ['query']),
  'getTotalOutstandingCredit' : IDL.Func([], [IDL.Float64], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveSetup' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateDaySales' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DaySales = IDL.Record({
    'id' : IDL.Nat,
    'pump1_n2_open' : IDL.Float64,
    'pump2_n1_close' : IDL.Float64,
    'dieselPrice' : IDL.Float64,
    'pump2_n2_close' : IDL.Float64,
    'pump2_n3_open' : IDL.Float64,
    'date' : IDL.Text,
    'pump1_n1_close' : IDL.Float64,
    'testPetrol' : IDL.Float64,
    'pump2_n3_close' : IDL.Float64,
    'pump1_n3_open' : IDL.Float64,
    'pump2_n1_open' : IDL.Float64,
    'pump1_n2_close' : IDL.Float64,
    'pump2_n4_close' : IDL.Float64,
    'pump1_n1_open' : IDL.Float64,
    'creditGiven' : IDL.Float64,
    'pump2_n4_open' : IDL.Float64,
    'pump1_n3_close' : IDL.Float64,
    'pump1_n4_close' : IDL.Float64,
    'testDiesel' : IDL.Float64,
    'pump1_n4_open' : IDL.Float64,
    'pump2_n2_open' : IDL.Float64,
    'petrolPrice' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CreditSettlement = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'amountSettled' : IDL.Float64,
  });
  const BunkSetup = IDL.Record({
    'bunkName' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCreditSettlement' : IDL.Func([IDL.Text, IDL.Float64], [], []),
    'addDaySales' : IDL.Func(
        [
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteDaySalesByDate' : IDL.Func([IDL.Text], [], []),
    'getAllDaySales' : IDL.Func([], [IDL.Vec(DaySales)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCreditSettlements' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(CreditSettlement)],
        ['query'],
      ),
    'getDaySalesByDate' : IDL.Func([IDL.Text], [IDL.Opt(DaySales)], ['query']),
    'getSetup' : IDL.Func([], [IDL.Opt(BunkSetup)], ['query']),
    'getTotalOutstandingCredit' : IDL.Func([], [IDL.Float64], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveSetup' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateDaySales' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };